update ci for  token validation

diff --git a/.github/workflows/camunda-ci.yml b/.github/workflows/camunda-ci.yml
--- a/.github/workflows/camunda-ci.yml
+++ b/.github/workflows/camunda-ci.yml
@@ -37,20 +37,27 @@ jobs:
       - name: Get Bearer Token
         id: get_token
         run: |
-            RESPONSE=$(curl -s --request POST \
-              --url https://login.cloud.camunda.io/oauth/token \
-              --header 'content-type: application/json' \
-              --data '{
-                "grant_type":"client_credentials",
-                "client_id":"${{ secrets.CAMUNDA_CLIENT_ID }}",
-                "client_secret":"${{ secrets.CAMUNDA_CLIENT_SECRET }}",
-                "audience":"${{ secrets.CAMUNDA_AUTH_AUDIENCE }}"
-              }')
-            
-            echo "RESPONSE: $RESPONSE"
-            ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
-            echo "::add-mask::$ACCESS_TOKEN"
-            echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
+          RESPONSE=$(curl -s --request POST \
+            --url https://login.cloud.camunda.io/oauth/token \
+            --header 'content-type: application/json' \
+            --data '{
+              "grant_type":"client_credentials",
+              "client_id":"${{ secrets.CAMUNDA_CLIENT_ID }}",
+              "client_secret":"${{ secrets.CAMUNDA_CLIENT_SECRET }}",
+              "audience":"${{ secrets.CAMUNDA_AUTH_AUDIENCE }}"
+            }')
+
+          echo "TOKEN RESPONSE: $RESPONSE"  # show full response for debugging
+
+          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
+
+          if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
+            echo "❌ Failed to extract access_token from response"
+            exit 1
+          fi
+
+          echo "::add-mask::$ACCESS_TOKEN"
+          echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
 
       - name: Deploy models to Camunda SaaS
         run: |
